### ISSUE TITLE
`preamble.json` not updated for the records of part 2

### ISSUE THREAD

**Issue by aayush105** [computerclubkec/constitution-of-nepal-dataset#16]

**Comment by varshalohakre** [comment]
hi! i would like to work on this issue. 
can you please provide a description of what needs to be done?

**Comment by aayush105** [comment]
> hi! i would like to work on this issue. can you please provide a description of what needs to be done?

This issue is already solved .
If you want to contribute to this repo its easy to contribute, you can read the README.md file, there you can get what need to be done and all this constitution data are added from a pdf which is already add in this repo itself. So you can go through that pdf and add the articles for various Parts and create a PR.

**Comment by aayush105** [comment]
> > hi! i would like to work on this issue. can you please provide a description of what needs to be done?
> 
> This issue is already solved . If you want to contribute to this repo its easy to contribute, you can read the README.md file, there you can get what need to be done and all this constitution data are added from a pdf which is already add in this repo itself. So you can go through that pdf and add the articles for various Parts and create a PR.

@varshalohakre
