### ISSUE TITLE
[FIX]: Incorrect file paths in `index.json` for article files

### ISSUE THREAD

**Issue by aayush105** [computerclubkec/constitution-of-nepal-dataset#17]
In the `index.json` file, the paths for the article files are incorrectly listed as:

`"file": "articles/part1/article1.json"`

These should be updated to:

`"file": "sections/part1/article1.json"`

The file paths should reference `sections` instead of `articles` to match the correct file structure.

**Comment by jfmartinz** [comment]
can you assign this issue to me?

**Comment by jfmartinz** [comment]
In the file, this `"file": "articles/part1/article1.json"` occurred more than once. you mean just change it in every occurrence of it with this  `"file": "sections/part1/article1.json"`

**Comment by aayush105** [comment]
> In the file, this `"file": "articles/part1/article1.json"` occurred more than once. you mean just change it in every occurrence of it with this `"file": "sections/part1/article1.json"`

Yes change in every occurrence.

**Comment by jfmartinz** [comment]
Can you check these changes?

```json
{
	"title": "Constitution of Nepal",
	"preamble": {
		"file": "sections/preamble.json"
	},
	"parts": [
		{
			"part_number": 1,
			"title": "Preliminary",
			"sections": [
				{
					"article_number": 1,
					"title": "Constitution as the fundamental law",
					"file": "sections/part1/article1.json"
				},
				{
					"article_number": 2,
					"title": "Sovereignty and state authority",
					"file": "sections/part1/article2.json"
				}
			]
		},
		{
			"part_number": 2,
			"title": "Citizenship",
			"sections": [
				{
					"article_number": 10,
					"title": "Not to deprive of citizenship",
					"file": "sections/part2/article10.json"
				},
				{
					"article_number": 11,
					"title": "To be citizens of Nepal",
					"file": "sections/part2/article11.json"
				},
				{
					"article_number": 12,
					"title": "Citizenship with identity of descent and gender",
					"file": "sections/part2/article12.json"
				},
				{
					"article_number": 13,
					"title": "Acquisition, reacquisition and termination of citizenship",
					"file": "sections/part2/article13.json"
				},
				{
					"article_number": 14,
					"title": "Power to grant non-resident Nepalese citizenship",
					"file": "sections/part2/article14.json"
				},
				{
					"article_number": 15,
					"title": "Other provisions relating to citizenship of Nepal",
					"file": "sections/part2/article15.json"
				}
			]
		}
	]
}

```

**Comment by jfmartinz** [comment]
I updated it already with the new name 'sections'.

**Comment by aayush105** [comment]
> I updated it already with the new name 'sections'.

yes, the update you did is correct, but can you pull the main branch again as in the part 1 other articles are also added. If you create a PR now it will so conflict so to avoid that 1st pull the main branch again and then make your changes and create a PR.
