### ISSUE TITLE
[FIX] : Incorrect folder name in the repository structure of README.md

### ISSUE THREAD

**Issue by aayush105** [computerclubkec/constitution-of-nepal-dataset#18]
The `README.md` file currently shows the folder hierarchy with the directory name `articles/`. However, the folder structure has been updated, and the directory name should be `sections/` instead. 

The file paths and references in the repository structure diagram, as well as any mention of `articles/`, should be updated to `sections/` to reflect the correct structure.

**Comment by aayush105** [comment]
You can refer to the attached image where the directory name `articles/` is highlighted in the repository structure. This needs to be updated to `sections/` to reflect the correct structure across the repository.
And there may be in other places as well so update it all.

![Screenshot 2024-10-10 202153](https://github.com/user-attachments/assets/951e5ade-d912-43cf-a196-baa05d01e19c)

**Comment by jfmartinz** [comment]
I think this is similar to this issue #17

**Comment by aayush105** [comment]
> I think this is similar to this issue #17

Yes, it is similar to the #17  issue, you can work on this as well. 
And Also you can contribute to the other part as well, by reading the README.md file you will get the insight of how to contribute.
@jfmartinz
