### ISSUE TITLE
Naming `section` is inappropriate.

### ISSUE THREAD

**Issue by thegauravgiri** [computerclubkec/constitution-of-nepal-dataset#5]
Rather than naming Section, it should be Article.
Eg. `section1` -> `article1`

**Comment by aayush105** [comment]
> Rather than naming Section, it should be Article. Eg. `section1` -> `article1`

ok, i will change it to article when I create a next PR.

**Comment by thegauravgiri** [comment]
I think better to have a separate PR for this issue only.
